# -*- coding: utf-8-unix -*-

# キーバインドを設定
unbind C-b
set-option -g prefix C-x
bind C-x send-prefix
set -g mode-keys emacs
set-option -s set-clipboard off
set-option -s copy-command 'xsel -b' # for Linux
# set-option -s copy-command 'pbcopy' # for macOS

# ステータスラインの色を設定
set-option -g status-bg white
set-window-option -g window-status-current-style fg=white,bg=blue,bold

# ステータスラインにGitブランチ名を表示
# @git_branch はzshのフックから更新される（files/.zshrc参照）
set-option -g status-right '#{@git_branch}'
set-option -g status-right-length 50

# Prefixキー押下時にステータスラインに反映
# https://stackoverflow.com/a/15308651
set-option -g status-left '#{?client_prefix,#[reverse][^x]#[noreverse],    } '

set-option -g status-interval 0
